// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carnegie.KycAggregationApi.Infrastructure.Migrations;

[DbContext(typeof(KycDbContext))]
[Migration("20260609173712_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

        modelBuilder.Entity("Carnegie.KycAggregationApi.Domain.AggregatedKycData", b =>
            {
                b.Property<string>("Ssn")
                    .HasColumnType("TEXT");

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasColumnType("TEXT");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int?>("Income")
                    .HasColumnType("INTEGER");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("TEXT");

                b.Property<string>("TaxCountry")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Ssn");

                b.ToTable("KycData");
            });
#pragma warning restore 612, 618
    }
}
